In [3]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)
print(np.shape(a))

[1 2 3 4 5]
(5,)


In [5]:
b = np.array([[1,2,3,4],[1,2,3,4]])
print(b)


[[1 2 3 4]
 [1 2 3 4]]


In [6]:
#dtype
c = np.array([1,2,3],dtype=complex)
print(c)

[1.+0.j 2.+0.j 3.+0.j]


In [7]:
#np.arange
d = np.arange(0,30,5)
print(d)

[ 0  5 10 15 20 25]


In [8]:
# reshape
np.arange(1,5,1).reshape(1,4)

array([[1, 2, 3, 4]])

In [9]:
#np.ones and np.zeros
np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#np.random
np.random.random((2,2)) #initialize with numbers between 0 nad 1


array([[0.94060572, 0.88629736],
       [0.91464318, 0.49335203]])

In [11]:
#np.linspace
np.linspace(-15,15,5)

array([-15. ,  -7.5,   0. ,   7.5,  15. ])